In [1]:
import pandas as pd

In [64]:
df = pd.read_csv('/kaggle/input/kaggle-dataset/train.csv')
test_df = pd.read_csv('/kaggle/input/kaggle-dataset/test.csv')

In [65]:
df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,Ford,F-150 Lariat,2018,74349,Gasoline,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Blue,Gray,None reported,Yes,11000
1,1,BMW,335 i,2007,80000,Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed M/T,Black,Black,None reported,Yes,8250
2,2,Jaguar,XF Luxury,2009,91491,Gasoline,300.0HP 4.2L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,Purple,Beige,None reported,Yes,15000
3,3,BMW,X7 xDrive40i,2022,2437,Hybrid,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Gray,Brown,None reported,Yes,63500
4,4,Pontiac,Firebird Base,2001,111000,Gasoline,200.0HP 3.8L V6 Cylinder Engine Gasoline Fuel,A/T,White,Black,None reported,Yes,7850

In [66]:
df.shape

(54273, 13)

In [67]:
df.describe()

                 id    model_year         milage         price
count  54273.000000  54273.000000   54273.000000  5.427300e+04
mean   27136.000000   2015.091979   72746.175667  3.921844e+04
std    15667.409917      5.588909   50469.490448  7.282634e+04
min        0.000000   1974.000000     100.000000  2.000000e+03
25%    13568.000000   2012.000000   32268.000000  1.550000e+04
50%    27136.000000   2016.000000   66107.000000  2.800000e+04
75%    40704.000000   2019.000000  102000.000000  4.500000e+04
max    54272.000000   2024.000000  405000.000000  2.954083e+06

In [68]:
df.columns

Index(['id', 'brand', 'model', 'model_year', 'milage', 'fuel_type', 'engine',
       'transmission', 'ext_col', 'int_col', 'accident', 'clean_title',
       'price'],
      dtype='object')

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54273 entries, 0 to 54272
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            54273 non-null  int64
 1   brand         54273 non-null  object
 2   model         54273 non-null  object
 3   model_year    54273 non-null  int64
 4   milage        54273 non-null  int64
 5   fuel_type     54273 non-null  object
 6   engine        54273 non-null  object
 7   transmission  54273 non-null  object
 8   ext_col       54273 non-null  object
 9   int_col       54273 non-null  object
 10  accident      54273 non-null  object
 11  clean_title   54273 non-null  object
 12  price         54273 non-null  int64
dtypes: int64(4), object(9)
memory usage: 5.4+ MB

In [70]:
def show_uniques():
    for i in df.columns:
      print(f"{i} - {len(df[i].unique())} - {df[i][0]}")

In [71]:
len(df['brand'].unique())

53

In [72]:
len(df['fuel_type'].unique())

7

In [73]:
df[df['fuel_type'] == 'not supported']

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
1069,1069,Toyota,Mirai Base,2016,40000,not supported,151.0HP Electric Motor Hydrogen Fuel,A/T,Silver,Black,None reported,Yes,14000
9621,9621,Toyota,Mirai Limited,2023,29553,not supported,182.0HP Electric Motor Hydrogen Fuel,A/T,Silver,Gray,None reported,Yes,9995
11441,11441,Toyota,Mirai Limited,2018,40000,not supported,182.0HP Electric Motor Hydrogen Fuel,A/T,Silver,Gray,None reported,Yes,7500
21771,21771,Nissan,Armada Platinum,2017,92000,not supported,390.0HP 5.6L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Gray,Black,None reported,Yes,20900

In [74]:
len(df['engine'].unique())

1061

In [75]:
df['accident'].unique()

array(['None reported', 'At least 1 accident or damage reported'],
      dtype=object)

In [76]:
len(df['model'].unique())

1827

In [77]:
df[df['model'] == 'Mirai Limited']

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
9621,9621,Toyota,Mirai Limited,2023,29553,not supported,182.0HP Electric Motor Hydrogen Fuel,A/T,Silver,Gray,None reported,Yes,9995
11441,11441,Toyota,Mirai Limited,2018,40000,not supported,182.0HP Electric Motor Hydrogen Fuel,A/T,Silver,Gray,None reported,Yes,7500

In [78]:
df[df['clean_title'] != 'Yes']

Empty DataFrame
Columns: [id, brand, model, model_year, milage, fuel_type, engine, transmission, ext_col, int_col, accident, clean_title, price]
Index: []

In [79]:
df.drop(columns=['clean_title'] ,inplace=True)

In [80]:
test_df.drop(columns=['clean_title'] ,inplace=True)
test_df.sample(2)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident
15737,70010,McLaren,570S Base,2017,19600,Gasoline,562.0HP 3.8L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported
24441,78714,Audi,A4 2.0T Premium,2016,91843,Gasoline,211.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Beige,None reported

In [81]:
df.sample(5)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price
15360,15360,Land,Rover Range Rover 5.0L Supercharged,2018,63295,E85 Flex Fuel,510.0HP 5.0L 8 Cylinder Engine Flex Fuel Capab...,Transmission w/Dual Shift Mode,Blue,White,At least 1 accident or damage reported,42995
4352,4352,Toyota,Tundra SR5,2020,41500,Gasoline,381.0HP 5.7L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,Black,Brown,None reported,44800
51239,51239,Lexus,ES 350 Base,2008,146000,Gasoline,272.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,4495
8208,8208,Nissan,Versa 1.8 S,2011,165000,Gasoline,122.0HP 1.8L 4 Cylinder Engine Gasoline Fuel,A/T,Blue,–,At least 1 accident or damage reported,4200
2226,2226,Audi,A3 2.0T Premium,2018,36500,Gasoline,220.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Silver,At least 1 accident or damage reported,25500

In [82]:
show_uniques()

id - 54273 - 0
brand - 53 - Ford
model - 1827 - F-150 Lariat
model_year - 34 - 2018
milage - 3212 - 74349
fuel_type - 7 - Gasoline
engine - 1061 - 375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel
transmission - 46 - 10-Speed A/T
ext_col - 260 - Blue
int_col - 124 - Gray
accident - 2 - None reported
price - 1481 - 11000

In [48]:
!pip install category_encoders

Requirement already satisfied: category_encoders in /opt/conda/lib/python3.10/site-packages (2.6.3)
Requirement already satisfied: numpy>=1.14.0 in /opt/conda/lib/python3.10/site-packages (from category_encoders) (1.26.4)
Requirement already satisfied: scikit-learn>=0.20.0 in /opt/conda/lib/python3.10/site-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in /opt/conda/lib/python3.10/site-packages (from category_encoders) (1.11.4)
Requirement already satisfied: statsmodels>=0.9.0 in /opt/conda/lib/python3.10/site-packages (from category_encoders) (0.14.1)
Requirement already satisfied: pandas>=1.0.5 in /opt/conda/lib/python3.10/site-packages (from category_encoders) (2.2.1)
Requirement already satisfied: patsy>=0.5.1 in /opt/conda/lib/python3.10/site-packages (from category_encoders) (0.5.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas>=1.0.5->category_encoders) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.10/site-packages (from pandas>=1.0.5->category_encoders) (2023.4)
Requirement already satisfied: six in /opt/conda/lib/python3.10/site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from scikit-learn>=0.20.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn>=0.20.0->category_encoders) (3.2.0)
Requirement already satisfied: packaging>=21.3 in /opt/conda/lib/python3.10/site-packages (from statsmodels>=0.9.0->category_encoders) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging>=21.3->statsmodels>=0.9.0->category_encoders) (3.1.1)
WARNING: Error parsing requirements for aiohttp: [Errno 2] No such file or directory: '/opt/conda/lib/python3.10/site-packages/aiohttp-3.9.1.dist-info/METADATA'

In [49]:
from sklearn.preprocessing import OneHotEncoder ,LabelEncoder
from category_encoders import CountEncoder

In [83]:
ohe = OneHotEncoder(sparse=False ,drop='first' ,handle_unknown='ignore')
ohe_cols = ['fuel_type' ,'accident']
df_ohe = pd.DataFrame(ohe.fit_transform(df[ohe_cols]), columns=ohe.get_feature_names_out(ohe_cols))
# test_df_ohe = pd.DataFrame(ohe.fit_transform(test_df[ohe_cols]), columns=ohe.get_feature_names_out(ohe_cols))

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [84]:
test_df_ohe = pd.DataFrame(ohe.transform(test_df[ohe_cols]), columns=ohe.get_feature_names_out(ohe_cols))

In [85]:
test_df_ohe

,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_–,accident_None reported
0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
36178,0.0,1.0,0.0,0.0,0.0,0.0,1.0
36179,0.0,1.0,0.0,0.0,0.0,0.0,0.0
36180,0.0,1.0,0.0,0.0,0.0,0.0,1.0
36181,0.0,1.0,0.0,0.0,0.0,0.0,1.0
36182,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [86]:
df_ohe

,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_–,accident_None reported
0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...
54268,0.0,1.0,0.0,0.0,0.0,0.0,1.0
54269,1.0,0.0,0.0,0.0,0.0,0.0,0.0
54270,0.0,1.0,0.0,0.0,0.0,0.0,0.0
54271,0.0,1.0,0.0,0.0,0.0,0.0,1.0
54272,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [87]:
label_cols = ['brand', 'transmission', 'ext_col', 'int_col']
label_encoders = {col: LabelEncoder() for col in label_cols}
for col in label_cols:
    df[col + '_label'] = label_encoders[col].fit_transform(df[col])
    classes_seen = set(label_encoders[col].classes_)

    def handle_unseen_labels(value):
        if value in classes_seen:
            return label_encoders[col].transform([value])[0]
        else:
            return -1  # Special category for unseen labels
    
    test_df[col + '_label'] = test_df[col].apply(handle_unseen_labels)

In [88]:
test_df[test_df['brand_label'] == -1]

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,brand_label,transmission_label,ext_col_label,int_col_label
11715,65988,Saab,9-3 Aero,2005,106000,Gasoline,280.0HP 2.8L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Beige,None reported,-1,34,17,6
14106,68379,smart,Passport TrailSport,2023,13133,Gasoline,280.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,9-Speed A/T,Silver,Gray,None reported,-1,31,212,57
29533,83806,smart,ForTwo Pure,2008,61595,Gasoline,70.0HP 1.0L 3 Cylinder Engine Gasoline Fuel,5-Speed M/T,Blue,Beige,None reported,-1,10,26,6
32721,86994,Saab,9-3 Aero,2009,50000,Gasoline,280.0HP 2.8L V6 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Black,None reported,-1,14,249,9

In [89]:
df.sample()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price,brand_label,transmission_label,ext_col_label,int_col_label
33052,33052,Porsche,Macan Turbo,2016,39300,Gasoline,400.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,None reported,36000,41,34,100,9

In [90]:
freq_cols = ['model', 'engine']
freq_encoder = CountEncoder()
df[freq_cols] = freq_encoder.fit_transform(df[freq_cols])
test_df[freq_cols] = freq_encoder.transform(test_df[freq_cols])

In [91]:
df.sample(2)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price,brand_label,transmission_label,ext_col_label,int_col_label
12239,12239,Maserati,6,2021,12172,Gasoline,100,8-Speed Automatic,Blu,Black,None reported,44791,31,28,25,9
49717,49717,Chevrolet,16,2015,202,Gasoline,15,Transmission w/Dual Shift Mode,Black,Red,None reported,47500,9,43,17,95

In [92]:
test_df.sample(2)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,brand_label,transmission_label,ext_col_label,int_col_label
23640,77913,MINI,69.0,2009,90367,Gasoline,63.0,A/T,Silver,Black,None reported,30,34,212,9
22093,76366,Dodge,46.0,2014,89000,Gasoline,34.0,A/T,Black,Black,None reported,11,34,17,9

In [93]:
df_combined = pd.concat([df, df_ohe], axis=1)
test_df_combined = pd.concat([test_df, test_df_ohe], axis=1)

In [94]:
df_combined.drop(columns=ohe_cols + label_cols, inplace=True)
test_df_combined.drop(columns=ohe_cols + label_cols, inplace=True)

In [95]:
df_combined.sample(2)

,id,model,model_year,milage,engine,price,brand_label,transmission_label,ext_col_label,int_col_label,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_–,accident_None reported
16767,16767,174,2019,6200,95,98000,25,34,17,9,0.0,1.0,0.0,0.0,0.0,0.0,1.0
35625,35625,31,2016,70503,70,17500,8,14,17,9,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [96]:
test_df_combined.sample(2)

,id,model,model_year,milage,engine,brand_label,transmission_label,ext_col_label,int_col_label,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_–,accident_None reported
22655,76928,117.0,2015,95000,39.0,14,34,249,57,0.0,1.0,0.0,0.0,0.0,0.0,1.0
6454,60727,98.0,2012,108045,55.0,14,14,100,9,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [97]:
import pickle
with open('/kaggle/working/ohe.pickle' ,'wb') as file:
    pickle.dump(ohe ,file)

with open('/kaggle/working/freq_encoder.pickle' ,'wb') as file:
    pickle.dump(freq_encoder ,file)

with open('/kaggle/working/label_encoder.pickle' ,'wb') as file:
    pickle.dump(label_encoders ,file)

In [98]:
import numpy as np

In [99]:
X = df_combined.drop(columns=['price'])
y = np.log(df_combined['price'])

In [101]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X ,y ,test_size=0.10 ,random_state=2)

In [102]:
X_train.shape ,X_test.shape

((48845, 16), (5428, 16))

In [103]:
from sklearn.linear_model import LinearRegression ,Lasso ,Ridge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor ,GradientBoostingRegressor ,AdaBoostRegressor ,ExtraTreesRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor,StackingRegressor

In [104]:
from sklearn.metrics import r2_score ,mean_absolute_error
from sklearn.preprocessing import StandardScaler

In [105]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [106]:
lr_reg = LinearRegression()
lr_reg.fit(X_train ,y_train)

y_pred = lr_reg.predict(X_test)
print('R2 Score : ',r2_score(y_test ,y_pred ))
print('MAE : ',mean_absolute_error(y_test ,y_pred))

R2 Score :  0.5424251347913561
MAE :  0.398854534491399

In [107]:
ridge = Ridge(alpha=10)
ridge.fit(X_train ,y_train)

y_pred = ridge.predict(X_test)
print('R2 Score : ',r2_score(y_test ,y_pred ))
print('MAE : ',mean_absolute_error(y_test ,y_pred))

R2 Score :  0.5424217970916445
MAE :  0.39885732419814884

In [108]:
dtr = DecisionTreeRegressor(max_depth=8)
dtr.fit(X_train ,y_train)

y_pred = dtr.predict(X_test)
print('R2 Score : ',r2_score(y_test ,y_pred ))
print('MAE : ',mean_absolute_error(y_test ,y_pred))

R2 Score :  0.5729481651980686
MAE :  0.38059748223284706

In [109]:
rf = RandomForestRegressor(n_estimators=100 ,
                              random_state=3 ,
                              max_samples=0.5 ,
                              max_features=0.75,
                              max_depth=15
                              )
rf.fit(X_train ,y_train)

y_pred = rf.predict(X_test)
print('R2 Score : ',r2_score(y_test ,y_pred ))
print('MAE : ',mean_absolute_error(y_test ,y_pred))

R2 Score :  0.6325003231596626
MAE :  0.34824773763928674

In [110]:
xtr = ExtraTreesRegressor(n_estimators=100,
                              random_state=3,
                              max_samples=0.5,
                              max_features=0.75,
                              max_depth=15,
                              bootstrap=True)
xtr.fit(X_train ,y_train)

y_pred = xtr.predict(X_test)
print('R2 Score : ',r2_score(y_test ,y_pred ))
print('MAE : ',mean_absolute_error(y_test ,y_pred))

R2 Score :  0.6181926140037558
MAE :  0.35814282391233754

In [111]:

y_pred = xtr.predict(X_train)
print('R2 Score : ',r2_score(y_train ,y_pred))
print('MAE : ',mean_absolute_error(y_train ,y_pred))

R2 Score :  0.7267448739542655
MAE :  0.30861662145678515

In [112]:
gbr = GradientBoostingRegressor(n_estimators=500)
gbr.fit(X_train ,y_train)

y_pred = gbr.predict(X_test)
print('R2 Score : ',r2_score(y_test ,y_pred ))
print('MAE : ',mean_absolute_error(y_test ,y_pred))

R2 Score :  0.6424883165722653
MAE :  0.3433546682623808

In [113]:
X_train.shape

(48845, 16)

# ANN

In [52]:
import tensorflow as tf

2024-06-02 14:47:36.093376: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-02 14:47:36.093507: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-02 14:47:36.221960: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

In [53]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128 ,activation='relu' ,input_shape=(X_train.shape[1] ,)),
    tf.keras.layers.Dropout(0.2),  # Dropout layer for regularization

    tf.keras.layers.Dense(64 ,activation='relu'),
    tf.keras.layers.Dropout(0.2),  # Dropout layer for regularization

    tf.keras.layers.Dense(32 ,activation='relu'),
    tf.keras.layers.Dropout(0.2),  # Dropout layer for regularization
    
    tf.keras.layers.Dense(16 ,activation='relu'),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [54]:
early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

history = model.fit(X_train, y_train, epochs=100, validation_split=0.2, batch_size=32, verbose=1, callbacks=[early_stopping])

Epoch 1/100
  97/1086 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50.2984 - mae: 6.1578

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1717339673.142711     112 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

1086/1086 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 12.2812 - mae: 2.3842 - val_loss: 1.7153 - val_mae: 1.1774
Epoch 2/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 1.5084 - mae: 0.9596 - val_loss: 3.9828 - val_mae: 1.8993
Epoch 3/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.8615 - mae: 0.7097 - val_loss: 2.4996 - val_mae: 1.4654
Epoch 4/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.5681 - mae: 0.5681 - val_loss: 1.5830 - val_mae: 1.1249
Epoch 5/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.4374 - mae: 0.4927 - val_loss: 1.1313 - val_mae: 0.9128
Epoch 6/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3796 - mae: 0.4513 - val_loss: 0.5360 - val_mae: 0.5683
Epoch 7/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3496 - mae: 0.4296 - val_loss: 0.5753 - val_mae: 0.5937
Epoch 8/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3374 - mae: 0.4199 - val_loss: 0.4351 - val_mae: 0.4891
Epoch 9/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3282 - mae: 0.4152 - val_loss: 0.3882 - val_mae: 0.4528
Epoch 10/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3211 - mae: 0.4053 - val_loss: 0.4099 - val_mae: 0.4731
Epoch 11/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3158 - mae: 0.4016 - val_loss: 0.3385 - val_mae: 0.4181
Epoch 12/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3101 - mae: 0.3985 - val_loss: 0.3605 - val_mae: 0.4324
Epoch 13/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3118 - mae: 0.3990 - val_loss: 0.3357 - val_mae: 0.4172
Epoch 14/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3027 - mae: 0.3917 - val_loss: 0.3483 - val_mae: 0.4236
Epoch 15/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3094 - mae: 0.3950 - val_loss: 0.3029 - val_mae: 0.3898
Epoch 16/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2994 - mae: 0.3900 - val_loss: 0.3113 - val_mae: 0.3947
Epoch 17/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2929 - mae: 0.3839 - val_loss: 0.3648 - val_mae: 0.4376
Epoch 18/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3009 - mae: 0.3885 - val_loss: 0.3048 - val_mae: 0.3911
Epoch 19/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2897 - mae: 0.3835 - val_loss: 0.3370 - val_mae: 0.4148
Epoch 20/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2950 - mae: 0.3862 - val_loss: 0.3325 - val_mae: 0.4116
Epoch 21/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2929 - mae: 0.3859 - val_loss: 0.3110 - val_mae: 0.3952
Epoch 22/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2906 - mae: 0.3813 - val_loss: 0.3004 - val_mae: 0.3866
Epoch 23/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2919 - mae: 0.3827 - val_loss: 0.4112 - val_mae: 0.4741
Epoch 24/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2979 - mae: 0.3862 - val_loss: 0.3360 - val_mae: 0.4145
Epoch 25/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2863 - mae: 0.3799 - val_loss: 0.3016 - val_mae: 0.3894
Epoch 26/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2823 - mae: 0.3778 - val_loss: 0.3338 - val_mae: 0.4158
Epoch 27/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2834 - mae: 0.3775 - val_loss: 0.3081 - val_mae: 0.3921
Epoch 28/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2841 - mae: 0.3779 - val_loss: 0.3538 - val_mae: 0.4324
Epoch 29/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2908 - mae: 0.3787 - val_loss: 0.2896 - val_mae: 0.3802
Epoch 30/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2838 - mae: 0.3767 - val_loss: 0.3121 - val_mae: 0.3967
Epoch 31/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2833 - mae: 0.3757 - val_loss: 0.2914 - val_mae: 0.3798
Epoch 32/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2811 - mae: 0.3737 - val_loss: 0.3271 - val_mae: 0.4088
Epoch 33/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2894 - mae: 0.3817 - val_loss: 0.3021 - val_mae: 0.3902
Epoch 34/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2766 - mae: 0.3738 - val_loss: 0.3485 - val_mae: 0.4270
Epoch 35/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2762 - mae: 0.3752 - val_loss: 0.3288 - val_mae: 0.4105
Epoch 36/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2869 - mae: 0.3787 - val_loss: 0.3021 - val_mae: 0.3895
Epoch 37/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2790 - mae: 0.3757 - val_loss: 0.3272 - val_mae: 0.4096
Epoch 38/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2781 - mae: 0.3742 - val_loss: 0.3022 - val_mae: 0.3877
Epoch 39/100
1086/1086 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2783 - mae: 0.3747 - val_loss: 0.3183 - val_mae: 0.4015

In [55]:
y_pred = model.predict(X_test)
y_pred.shape

340/340 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

(10855, 1)

In [56]:
y_pred

array([[10.639207],
       [ 9.729893],
       [10.135698],
       ...,
       [10.700788],
       [ 9.095932],
       [ 9.950303]], dtype=float32)

In [57]:
y_pred = y_pred.flatten()  # Flatten the predictions to match the shape of y_test
y_pred.shape

(10855,)

In [58]:
y_pred

array([10.639207,  9.729893, 10.135698, ..., 10.700788,  9.095932,
        9.950303], dtype=float32)

In [59]:

print('R2 Score : ',r2_score(y_test ,y_pred ))
print('MAE : ',mean_absolute_error(y_test ,y_pred))

R2 Score :  0.5894965219546082
MAE :  0.37298654653403024

In [60]:
import keras_tuner as kt
from keras import Sequential
from keras.layers import Dense ,Dropout

In [61]:
def build_model(hp):
    model = Sequential()
    
    counter = 0
    
    for i in range(hp.Int('num_layers' ,min_value=1 ,max_value=10)):
        if counter == 0:
            model.add(Dense(units=hp.Int('units' + str(i), min_value=32, max_value=512, step=32),
                                            activation= hp.Choice('activation' + str(i) ,values=['tanh','relu','sigmoid']), 
                                            input_shape=(X_train.shape[1],)))
            
            model.add(Dropout(hp.Float('dropout' + str(i), min_value=0.0, max_value=0.9, step=0.1)))
            
        else:
            model.add(Dense(units=hp.Int('units' + str(i), min_value=32, max_value=512, step=32),
                                            activation= hp.Choice('activation' + str(i) ,values=['tanh','relu','sigmoid'])))
            
            model.add(Dropout(hp.Float('dropout' + str(i), min_value=0.0, max_value=0.9, step=0.1)))
                      
    counter = counter + 1
            
    model.add(Dense(1))
                      
    model.compile(optimizer= hp.Choice('optimizer' ,values=['adam','sgd','nadam','adadelta','rmsprop']), 
                  loss='mean_squared_error', 
                  metrics=['mae'])
    return model

In [63]:
tuner = kt.GridSearch(build_model ,
                        objective='val_loss' ,
                        max_trials=50 ,
                        directory='mydir',
                        project_name='final')

stop_early = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10)

tuner.search(X_train, y_train, epochs=50, validation_data=(X_test ,y_test), callbacks=[stop_early])

Trial 50 Complete [00h 01m 32s]
val_loss: 0.2760912775993347

Best val_loss So Far: 0.2760912775993347
Total elapsed time: 01h 36m 18s

In [64]:
best_hps = tuner.get_best_hyperparameters()[0].values
best_hps

{'num_layers': 1,
 'units0': 32,
 'activation0': 'relu',
 'dropout0': 0.0,
 'optimizer': 'rmsprop'}

In [65]:
model = tuner.get_best_models(num_models=1)[0]
model.summary()

/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/opt/conda/lib/python3.10/site-packages/keras/src/saving/saving_lib.py:415: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 577 (2.25 KB)

 Trainable params: 577 (2.25 KB)

 Non-trainable params: 0 (0.00 B)

In [66]:
history = model.fit(X_train, y_train, epochs=500, validation_data=(X_test ,y_test), callbacks=[stop_early] ,initial_epoch=100 ,batch_size=32)

Epoch 101/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.2937 - mae: 0.3789 - val_loss: 0.2790 - val_mae: 0.3776
Epoch 102/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3232 - mae: 0.3811 - val_loss: 0.2779 - val_mae: 0.3736
Epoch 103/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3436 - mae: 0.3822 - val_loss: 0.2793 - val_mae: 0.3784
Epoch 104/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3059 - mae: 0.3792 - val_loss: 0.2800 - val_mae: 0.3821
Epoch 105/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2865 - mae: 0.3787 - val_loss: 0.2829 - val_mae: 0.3834
Epoch 106/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3042 - mae: 0.3779 - val_loss: 0.2795 - val_mae: 0.3763
Epoch 107/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3104 - mae: 0.3794 - val_loss: 0.2791 - val_mae: 0.3766
Epoch 108/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2991 - mae: 0.3802 - val_loss: 0.2796 - val_mae: 0.3765
Epoch 109/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3020 - mae: 0.3812 - val_loss: 0.2761 - val_mae: 0.3738
Epoch 110/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3050 - mae: 0.3799 - val_loss: 0.2787 - val_mae: 0.3793
Epoch 111/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3054 - mae: 0.3818 - val_loss: 0.2821 - val_mae: 0.3812
Epoch 112/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2951 - mae: 0.3751 - val_loss: 0.2782 - val_mae: 0.3755
Epoch 113/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3042 - mae: 0.3807 - val_loss: 0.2774 - val_mae: 0.3751
Epoch 114/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3066 - mae: 0.3800 - val_loss: 0.2793 - val_mae: 0.3813
Epoch 115/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2902 - mae: 0.3792 - val_loss: 0.2852 - val_mae: 0.3841
Epoch 116/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2990 - mae: 0.3776 - val_loss: 0.2762 - val_mae: 0.3736
Epoch 117/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3135 - mae: 0.3827 - val_loss: 0.2909 - val_mae: 0.3929
Epoch 118/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2915 - mae: 0.3794 - val_loss: 0.2766 - val_mae: 0.3760
Epoch 119/500
1357/1357 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3002 - mae: 0.3796 - val_loss: 0.2767 - val_mae: 0.3741

In [67]:
y_pred = model.predict(X_test)
y_pred = y_pred.flatten()

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print('R2 Score:', r2)
print('MAE:', mae)

340/340 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
R2 Score: 0.5928270237849185
MAE: 0.37414936004113714

In [69]:
import pickle 
with open('/kaggle/working/ann_model.pickle' ,'wb') as file:
    pickle.dump(model ,file)
with open('/kaggle/working/gbr_model.pickle' ,'wb') as file:
    pickle.dump(gbr ,file)
with open('/kaggle/working/rf_model.pickle' ,'wb') as file:
    pickle.dump(rf ,file)

In [114]:
test_df_combined.sample(2)

,id,model,model_year,milage,engine,brand_label,transmission_label,ext_col_label,int_col_label,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_–,accident_None reported
34674,88947,780.0,2021,44362,353.0,14,3,0,9,0.0,1.0,0.0,0.0,0.0,0.0,1.0
9009,63282,12.0,2017,91600,160.0,17,14,188,9,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [139]:
ids = test_df_combined['id']
ids.shape

(36183,)

In [116]:
X_test = test_df_combined
X_test.shape

(36183, 16)

In [117]:
X_test = scaler.transform(X_test)

In [119]:
X_test

array([[ 1.73231113,  1.623729  , -0.19552453, ..., -0.00904977,
        -0.07483194,  0.6003926 ],
       [ 1.73237499,  0.45808442, -0.0165944 , ..., -0.00904977,
        -0.07483194,  0.6003926 ],
       [ 1.73243884, -0.61934921, -0.0165944 , ..., -0.00904977,
        -0.07483194,  0.6003926 ],
       ...,
       [ 4.0426302 , -0.34841561, -0.73231491, ..., -0.00904977,
        -0.07483194,  0.6003926 ],
       [ 4.04269405, -0.14048982,  0.69912611, ..., -0.00904977,
        -0.07483194,  0.6003926 ],
       [ 4.04275791, -0.27280623, -0.55338478, ..., -0.00904977,
        -0.07483194, -1.66557683]])

In [121]:
# y_test_pred_ann = model.predict(X_test)
y_test_pred_gbr = gbr.predict(X_test)
y_test_pred_rf = rf.predict(X_test)

In [136]:
gbr_pred = np.exp(y_test_pred_gbr)
gbr_pred.shape

(36183,)

In [137]:
rf_pred = np.exp(y_test_pred_rf)
rf_pred.shape

(36183,)

In [140]:
ids

0        54273
1        54274
2        54275
3        54276
4        54277
         ...
36178    90451
36179    90452
36180    90453
36181    90454
36182    90455
Name: id, Length: 36183, dtype: int64

In [143]:
gbr_final = {
    'id' : ids,
    'price' : gbr_pred
}
gbr_df = pd.DataFrame(gbr_final)
gbr_df

          id         price
0      54273  15570.117822
1      54274  19456.701350
2      54275  29533.747003
3      54276  42439.542947
4      54277  29089.874011
...      ...           ...
36178  90451  63274.812624
36179  90452   6948.017541
36180  90453   9686.612096
36181  90454  43015.146892
36182  90455   9685.414431

[36183 rows x 2 columns]

In [148]:
gbr_df.to_csv('/kaggle/working/submission_gbr.csv' ,index=False)

In [144]:
rf_final = {
    'id' : ids,
    'price' : rf_pred
}
rf_df = pd.DataFrame(rf_final)
rf_df

          id         price
0      54273  24162.036136
1      54274  18977.020864
2      54275  32420.603418
3      54276  43810.733674
4      54277  33574.186067
...      ...           ...
36178  90451  51418.407873
36179  90452   9186.399952
36180  90453   9798.118370
36181  90454  44927.994254
36182  90455  13106.933190

[36183 rows x 2 columns]

In [147]:
rf_df.to_csv('/kaggle/working/submission_rf.csv' ,index=False)

In [123]:
y_train

37886    10.356154
34661    11.552146
31308    10.526749
29879    10.858999
5245     10.714418
           ...
44566     9.614471
30280    10.373491
6637     10.818778
35343     9.392662
23720    11.042922
Name: price, Length: 48845, dtype: float64

In [126]:
np.exp(y_train)

37886     31450.0
34661    104000.0
31308     37300.0
29879     52000.0
5245      45000.0
           ...
44566     14980.0
30280     32000.0
6637      49950.0
35343     12000.0
23720     62500.0
Name: price, Length: 48845, dtype: float64

In [129]:
df_combined[df_combined['id'] == 34661]

,id,model,model_year,milage,engine,price,brand_label,transmission_label,ext_col_label,int_col_label,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_–,accident_None reported
34661,34661,102,2022,9400,97,104000,51,34,100,9,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [152]:
y_test_pred_lr = lr_reg.predict(X_test)
y_test_pred_ridge = ridge.predict(X_test)
y_test_pred_dtr = dtr.predict(X_test)
y_test_pred_xtr = xtr.predict(X_test)

In [153]:
lr_pred = np.exp(y_test_pred_lr)
lr_pred.shape
ridge_pred = np.exp(y_test_pred_lr)
ridge_pred.shape
dtr_pred = np.exp(y_test_pred_dtr)
dtr_pred.shape
xtr_pred = np.exp(y_test_pred_xtr)
xtr_pred.shape

(36183,)

In [154]:
lr_final = {
    'id' : ids,
    'price' : lr_pred
}
lr_df = pd.DataFrame(lr_final)

ridge_final = {
    'id' : ids,
    'price' : ridge_pred
}
ridge_df = pd.DataFrame(ridge_final)

dtr_final = {
    'id' : ids,
    'price' : dtr_pred
}
dtr_df = pd.DataFrame(dtr_final)

xtr_final = {
    'id' : ids,
    'price' : xtr_pred
}
xtr_df = pd.DataFrame(xtr_final)

In [155]:
lr_df.to_csv('/kaggle/working/submission_lr.csv' ,index=False)
ridge_df.to_csv('/kaggle/working/submission_ridge.csv' ,index=False)
dtr_df.to_csv('/kaggle/working/submission_dtr.csv' ,index=False)
xtr_df.to_csv('/kaggle/working/submission_xtr.csv' ,index=False)

In [ ]:
svr = SVR(kernel='rbf' ,C=10000 ,epsilon=0.1)
svr.fit(X_train ,y_train)

y_pred = svr.predict(X_test)
print('R2 Score : ',r2_score(y_test ,y_pred ))
print('MAE : ',mean_absolute_error(y_test ,y_pred))

In [ ]:
from sklearn.ensemble import VotingRegressor,StackingRegressor

In [ ]:
rf = RandomForestRegressor(n_estimators=350,random_state=3,max_samples=0.5,max_features=0.75,max_depth=15 )
gbdt = GradientBoostingRegressor(n_estimators=100,max_features=0.5)
xgb = XGBRegressor(n_estimators=25,learning_rate=0.3,max_depth=5)
et = ExtraTreesRegressor(n_estimators=100,random_state=3,max_samples=0.5,max_features=0.75,max_depth=10,bootstrap=True)

vr = VotingRegressor([('rf', rf), ('gbdt', gbdt), ('xgb',xgb), ('et',et)],weights=[5,1,1,1])
vr.fit(X_train ,y_train)

y_pred = vr.predict(X_test)
print('R2 Score : ',r2_score(y_test ,y_pred ))
print('MAE : ',mean_absolute_error(y_test ,y_pred))

In [ ]:
estimators = [
    ('rf', RandomForestRegressor(n_estimators=350,random_state=3,max_samples=0.5,max_features=0.75,max_depth=15)),
    ('gbdt',GradientBoostingRegressor(n_estimators=100,max_features=0.5)),
    ('xgb', XGBRegressor(n_estimators=25,learning_rate=0.3,max_depth=5))
]

sr = StackingRegressor(estimators=estimators, final_estimator=Ridge(alpha=100))
sr.fit(X_train ,y_train)

y_pred = sr.predict(X_test)
print('R2 Score : ',r2_score(y_test ,y_pred ))
print('MAE : ',mean_absolute_error(y_test ,y_pred))